package onepassword

import (
	"github.com/hashicorp/terraform/helper/schema"
)

var sectionSchema = &schema.Resource{
	Schema: map[string]*schema.Schema{
		"name": {
			Type:        schema.TypeString,
			Computed:    true,
			Optional:    true,
			Description: "Item login section name.",
		},
		"field": {
			Type:        schema.TypeList,
			Computed:    true,
			Optional:    true,
			Description: "Item login section field.",
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"name": {
						Type:        schema.TypeString,
						Computed:    true,
						Optional:    true,
						Description: "Item login section field name.",
					},
					"string": {
						Type:        schema.TypeString,
						Computed:    true,
						Optional:    true,
						Description: "Item login section field value for string.",
						ConflictsWith: []string{
							"section.field.url",
							"section.field.phone",
							"section.field.email",
							"section.field.date",
							"section.field.month_year",
							"section.field.totp",
							"section.field.concealed",
							"section.field.address",
						},
					},
					"url": {
						Type:         schema.TypeString,
						Computed:     true,
						Optional:     true,
						ValidateFunc: urlValidate,
						Description:  "Item login section field value for url.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.phone",
							"section.field.email",
							"section.field.date",
							"section.field.month_year",
							"section.field.totp",
							"section.field.concealed",
							"section.field.address",
						},
					},
					"phone": {
						Type:        schema.TypeString,
						Computed:    true,
						Optional:    true,
						Description: "Item login section field value for phone.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.url",
							"section.field.email",
							"section.field.date",
							"section.field.month_year",
							"section.field.totp",
							"section.field.concealed",
							"section.field.address",
						},
					},
					"email": {
						Type:         schema.TypeString,
						Computed:     true,
						Optional:     true,
						ValidateFunc: emailValidate,
						Description:  "Item login section field value for email.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.url",
							"section.field.phone",
							"section.field.date",
							"section.field.month_year",
							"section.field.totp",
							"section.field.concealed",
							"section.field.address",
						},
					},
					"date": {
						Type:     schema.TypeInt,
						Computed: true,
						Optional: true,
						// ValidateFunc: dateValidate,
						Description: "Item login section field value for date.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.url",
							"section.field.phone",
							"section.field.email",
							"section.field.month_year",
							"section.field.totp",
							"section.field.concealed",
							"section.field.address",
						},
					},
					"month_year": {
						Type:     schema.TypeInt,
						Computed: true,
						Optional: true,
						// ValidateFunc: monthYearValidate,
						Description: "Item login section field value for month year.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.url",
							"section.field.phone",
							"section.field.email",
							"section.field.date",
							"section.field.totp",
							"section.field.concealed",
							"section.field.address",
						},
					},
					"totp": {
						Type:      schema.TypeString,
						Computed:  true,
						Optional:  true,
						Sensitive: true,
						// ValidateFunc: totpValidate,
						Description: "Item login section field value for totp.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.url",
							"section.field.phone",
							"section.field.email",
							"section.field.date",
							"section.field.month_year",
							"section.field.concealed",
							"section.field.address",
						},
					},
					"concealed": {
						Type:        schema.TypeString,
						Computed:    true,
						Optional:    true,
						Sensitive:   true,
						Description: "Item login section field value for password.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.url",
							"section.field.phone",
							"section.field.email",
							"section.field.date",
							"section.field.month_year",
							"section.field.totp",
							"section.field.address",
						},
					},
					"address": {
						Type:        schema.TypeMap,
						Computed:    true,
						Optional:    true,
						Description: "Item login section field value for address.",
						ConflictsWith: []string{
							"section.field.string",
							"section.field.url",
							"section.field.phone",
							"section.field.email",
							"section.field.date",
							"section.field.month_year",
							"section.field.totp",
							"section.field.concealed",
						},
						Elem: &schema.Resource{
							Schema: map[string]*schema.Schema{
								"country": {
									Type:        schema.TypeString,
									Computed:    true,
									Optional:    true,
									Description: "Item login section field value for address - country.",
								},
								"city": {
									Type:        schema.TypeString,
									Computed:    true,
									Optional:    true,
									Description: "Item login section field value for address - city.",
								},
								"region": {
									Type:        schema.TypeString,
									Computed:    true,
									Optional:    true,
									Description: "Item login section field value for address - region.",
								},
								"state": {
									Type:        schema.TypeString,
									Computed:    true,
									Optional:    true,
									Description: "Item login section field value for address - state.",
								},
								"street": {
									Type:        schema.TypeString,
									Computed:    true,
									Optional:    true,
									Description: "Item login section field value for address - street.",
								},
								"zip": {
									Type:        schema.TypeString,
									Computed:    true,
									Optional:    true,
									Description: "Item login section field value for address - zip.",
								},
							},
						},
					},
				},
			},
		},
	},
}
